<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="5" assertions="3" errors="2" warnings="0" failures="0" skipped="0" time="0.062141">
    <testsuite name="App" tests="5" assertions="3" errors="2" warnings="0" failures="0" skipped="0" time="0.062141">
      <testsuite name="ExampleDatabaseTest" file="/home/laravel/web/codeigniter/tests/database/ExampleDatabaseTest.php" tests="2" assertions="0" errors="2" warnings="0" failures="0" skipped="0" time="0.052159">
        <testcase name="testModelFindAll" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="/home/laravel/web/codeigniter/tests/database/ExampleDatabaseTest.php" line="17" assertions="0" time="0.051344">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testModelFindAll
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [SQLite3]: Class 'SQLite3' not found

/home/laravel/web/codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php:407
/home/laravel/web/codeigniter/vendor/codeigniter4/framework/system/Test/DatabaseTestTrait.php:74
/home/laravel/web/codeigniter/vendor/codeigniter4/framework/system/Test/DatabaseTestTrait.php:54
/home/laravel/web/codeigniter/vendor/codeigniter4/framework/system/Test/CIUnitTestCase.php:244</error>
        </testcase>
        <testcase name="testSoftDeleteLeavesRow" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="/home/laravel/web/codeigniter/tests/database/ExampleDatabaseTest.php" line="28" assertions="0" time="0.000815">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testSoftDeleteLeavesRow
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [SQLite3]: Class 'SQLite3' not found

/home/laravel/web/codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php:407
/home/laravel/web/codeigniter/vendor/codeigniter4/framework/system/Test/DatabaseTestTrait.php:74
/home/laravel/web/codeigniter/vendor/codeigniter4/framework/system/Test/DatabaseTestTrait.php:54
/home/laravel/web/codeigniter/vendor/codeigniter4/framework/system/Test/CIUnitTestCase.php:244</error>
        </testcase>
      </testsuite>
      <testsuite name="ExampleSessionTest" file="/home/laravel/web/codeigniter/tests/session/ExampleSessionTest.php" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.000773">
        <testcase name="testSessionSimple" class="ExampleSessionTest" classname="ExampleSessionTest" file="/home/laravel/web/codeigniter/tests/session/ExampleSessionTest.php" line="11" assertions="1" time="0.000773"/>
      </testsuite>
      <testsuite name="HealthTest" file="/home/laravel/web/codeigniter/tests/unit/HealthTest.php" tests="2" assertions="2" errors="0" warnings="0" failures="0" skipped="0" time="0.009209">
        <testcase name="testIsDefinedAppPath" class="HealthTest" classname="HealthTest" file="/home/laravel/web/codeigniter/tests/unit/HealthTest.php" line="13" assertions="1" time="0.000519"/>
        <testcase name="testBaseUrlHasBeenSet" class="HealthTest" classname="HealthTest" file="/home/laravel/web/codeigniter/tests/unit/HealthTest.php" line="18" assertions="1" time="0.008690"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
